
steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install dependencies'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build styleguide'
    args: ['run', 'styleguide']
    env:
      - 'BUILD_ID=$BUILD_ID'

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build'
    args: ['run', 'build']
    env:
      - 'BUILD_ID=$BUILD_ID'

  # Build snapshot images and push them to Google Cloud Registry

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build deployable image (commit tag)'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/styleguide-enit-systems:$SHORT_SHA', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push deployable image (commit tag)'
    args: ['push', 'gcr.io/$PROJECT_ID/styleguide-enit-systems:$SHORT_SHA']
    
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build deployable image (latest tag)'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/styleguide-enit-systems:latest', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push deployable image (latest tag)'
    args: ['push', 'gcr.io/$PROJECT_ID/styleguide-enit-systems:latest']
    
images:
  - 'gcr.io/$PROJECT_ID/styleguide-enit-systems:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/styleguide-enit-systems:latest'
